// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SubscribeResp.proto
// Protobuf Java Version: 4.27.0

package com.example.netty.chapter8.pojo;

public interface SubscribeRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chapter8.SubscribeResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 subReqId = 1;</code>
   * @return The subReqId.
   */
  int getSubReqId();

  /**
   * <code>int32 respCode = 2;</code>
   * @return The respCode.
   */
  int getRespCode();

  /**
   * <code>string desc = 3;</code>
   * @return The desc.
   */
  java.lang.String getDesc();
  /**
   * <code>string desc = 3;</code>
   * @return The bytes for desc.
   */
  com.google.protobuf.ByteString
      getDescBytes();
}
