// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SubscribeReq.proto
// Protobuf Java Version: 4.27.0

package com.example.netty.chapter8.pojo;

/**
 * Protobuf type {@code chapter8.SubscribeReq}
 */
public final class SubscribeReq extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:chapter8.SubscribeReq)
    SubscribeReqOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      SubscribeReq.class.getName());
  }
  // Use SubscribeReq.newBuilder() to construct.
  private SubscribeReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SubscribeReq() {
    userName_ = "";
    productName_ = "";
    address_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.netty.chapter8.pojo.SubscribeReqProtos.internal_static_chapter8_SubscribeReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.netty.chapter8.pojo.SubscribeReqProtos.internal_static_chapter8_SubscribeReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.netty.chapter8.pojo.SubscribeReq.class, com.example.netty.chapter8.pojo.SubscribeReq.Builder.class);
  }

  public static final int SUBREQID_FIELD_NUMBER = 1;
  private int subReqId_ = 0;
  /**
   * <code>int32 subReqId = 1;</code>
   * @return The subReqId.
   */
  @java.lang.Override
  public int getSubReqId() {
    return subReqId_;
  }

  public static final int USERNAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userName_ = "";
  /**
   * <code>string userName = 2;</code>
   * @return The userName.
   */
  @java.lang.Override
  public java.lang.String getUserName() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userName_ = s;
      return s;
    }
  }
  /**
   * <code>string userName = 2;</code>
   * @return The bytes for userName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserNameBytes() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCTNAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object productName_ = "";
  /**
   * <code>string productName = 3;</code>
   * @return The productName.
   */
  @java.lang.Override
  public java.lang.String getProductName() {
    java.lang.Object ref = productName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productName_ = s;
      return s;
    }
  }
  /**
   * <code>string productName = 3;</code>
   * @return The bytes for productName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductNameBytes() {
    java.lang.Object ref = productName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDRESS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList address_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string address = 4;</code>
   * @return A list containing the address.
   */
  public com.google.protobuf.ProtocolStringList
      getAddressList() {
    return address_;
  }
  /**
   * <code>repeated string address = 4;</code>
   * @return The count of address.
   */
  public int getAddressCount() {
    return address_.size();
  }
  /**
   * <code>repeated string address = 4;</code>
   * @param index The index of the element to return.
   * @return The address at the given index.
   */
  public java.lang.String getAddress(int index) {
    return address_.get(index);
  }
  /**
   * <code>repeated string address = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the address at the given index.
   */
  public com.google.protobuf.ByteString
      getAddressBytes(int index) {
    return address_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (subReqId_ != 0) {
      output.writeInt32(1, subReqId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, userName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(productName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, productName_);
    }
    for (int i = 0; i < address_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, address_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (subReqId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, subReqId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, userName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(productName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, productName_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < address_.size(); i++) {
        dataSize += computeStringSizeNoTag(address_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAddressList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.netty.chapter8.pojo.SubscribeReq)) {
      return super.equals(obj);
    }
    com.example.netty.chapter8.pojo.SubscribeReq other = (com.example.netty.chapter8.pojo.SubscribeReq) obj;

    if (getSubReqId()
        != other.getSubReqId()) return false;
    if (!getUserName()
        .equals(other.getUserName())) return false;
    if (!getProductName()
        .equals(other.getProductName())) return false;
    if (!getAddressList()
        .equals(other.getAddressList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUBREQID_FIELD_NUMBER;
    hash = (53 * hash) + getSubReqId();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUserName().hashCode();
    hash = (37 * hash) + PRODUCTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getProductName().hashCode();
    if (getAddressCount() > 0) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddressList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.netty.chapter8.pojo.SubscribeReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.netty.chapter8.pojo.SubscribeReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.netty.chapter8.pojo.SubscribeReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.netty.chapter8.pojo.SubscribeReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.netty.chapter8.pojo.SubscribeReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.netty.chapter8.pojo.SubscribeReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.netty.chapter8.pojo.SubscribeReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.netty.chapter8.pojo.SubscribeReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.netty.chapter8.pojo.SubscribeReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.netty.chapter8.pojo.SubscribeReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.netty.chapter8.pojo.SubscribeReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.netty.chapter8.pojo.SubscribeReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.netty.chapter8.pojo.SubscribeReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code chapter8.SubscribeReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:chapter8.SubscribeReq)
      com.example.netty.chapter8.pojo.SubscribeReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.netty.chapter8.pojo.SubscribeReqProtos.internal_static_chapter8_SubscribeReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.netty.chapter8.pojo.SubscribeReqProtos.internal_static_chapter8_SubscribeReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.netty.chapter8.pojo.SubscribeReq.class, com.example.netty.chapter8.pojo.SubscribeReq.Builder.class);
    }

    // Construct using com.example.netty.chapter8.pojo.SubscribeReq.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      subReqId_ = 0;
      userName_ = "";
      productName_ = "";
      address_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.netty.chapter8.pojo.SubscribeReqProtos.internal_static_chapter8_SubscribeReq_descriptor;
    }

    @java.lang.Override
    public com.example.netty.chapter8.pojo.SubscribeReq getDefaultInstanceForType() {
      return com.example.netty.chapter8.pojo.SubscribeReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.netty.chapter8.pojo.SubscribeReq build() {
      com.example.netty.chapter8.pojo.SubscribeReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.netty.chapter8.pojo.SubscribeReq buildPartial() {
      com.example.netty.chapter8.pojo.SubscribeReq result = new com.example.netty.chapter8.pojo.SubscribeReq(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.netty.chapter8.pojo.SubscribeReq result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.subReqId_ = subReqId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.userName_ = userName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.productName_ = productName_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        address_.makeImmutable();
        result.address_ = address_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.netty.chapter8.pojo.SubscribeReq) {
        return mergeFrom((com.example.netty.chapter8.pojo.SubscribeReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.netty.chapter8.pojo.SubscribeReq other) {
      if (other == com.example.netty.chapter8.pojo.SubscribeReq.getDefaultInstance()) return this;
      if (other.getSubReqId() != 0) {
        setSubReqId(other.getSubReqId());
      }
      if (!other.getUserName().isEmpty()) {
        userName_ = other.userName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getProductName().isEmpty()) {
        productName_ = other.productName_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.address_.isEmpty()) {
        if (address_.isEmpty()) {
          address_ = other.address_;
          bitField0_ |= 0x00000008;
        } else {
          ensureAddressIsMutable();
          address_.addAll(other.address_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              subReqId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              userName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              productName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureAddressIsMutable();
              address_.add(s);
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int subReqId_ ;
    /**
     * <code>int32 subReqId = 1;</code>
     * @return The subReqId.
     */
    @java.lang.Override
    public int getSubReqId() {
      return subReqId_;
    }
    /**
     * <code>int32 subReqId = 1;</code>
     * @param value The subReqId to set.
     * @return This builder for chaining.
     */
    public Builder setSubReqId(int value) {

      subReqId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 subReqId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSubReqId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      subReqId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object userName_ = "";
    /**
     * <code>string userName = 2;</code>
     * @return The userName.
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userName = 2;</code>
     * @return The bytes for userName.
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userName = 2;</code>
     * @param value The userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string userName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserName() {
      userName_ = getDefaultInstance().getUserName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string userName = 2;</code>
     * @param value The bytes for userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object productName_ = "";
    /**
     * <code>string productName = 3;</code>
     * @return The productName.
     */
    public java.lang.String getProductName() {
      java.lang.Object ref = productName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string productName = 3;</code>
     * @return The bytes for productName.
     */
    public com.google.protobuf.ByteString
        getProductNameBytes() {
      java.lang.Object ref = productName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string productName = 3;</code>
     * @param value The productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      productName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string productName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductName() {
      productName_ = getDefaultInstance().getProductName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string productName = 3;</code>
     * @param value The bytes for productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      productName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList address_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureAddressIsMutable() {
      if (!address_.isModifiable()) {
        address_ = new com.google.protobuf.LazyStringArrayList(address_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <code>repeated string address = 4;</code>
     * @return A list containing the address.
     */
    public com.google.protobuf.ProtocolStringList
        getAddressList() {
      address_.makeImmutable();
      return address_;
    }
    /**
     * <code>repeated string address = 4;</code>
     * @return The count of address.
     */
    public int getAddressCount() {
      return address_.size();
    }
    /**
     * <code>repeated string address = 4;</code>
     * @param index The index of the element to return.
     * @return The address at the given index.
     */
    public java.lang.String getAddress(int index) {
      return address_.get(index);
    }
    /**
     * <code>repeated string address = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the address at the given index.
     */
    public com.google.protobuf.ByteString
        getAddressBytes(int index) {
      return address_.getByteString(index);
    }
    /**
     * <code>repeated string address = 4;</code>
     * @param index The index to set the value at.
     * @param value The address to set.
     * @return This builder for chaining.
     */
    public Builder setAddress(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureAddressIsMutable();
      address_.set(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string address = 4;</code>
     * @param value The address to add.
     * @return This builder for chaining.
     */
    public Builder addAddress(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureAddressIsMutable();
      address_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string address = 4;</code>
     * @param values The address to add.
     * @return This builder for chaining.
     */
    public Builder addAllAddress(
        java.lang.Iterable<java.lang.String> values) {
      ensureAddressIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, address_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string address = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddress() {
      address_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string address = 4;</code>
     * @param value The bytes of the address to add.
     * @return This builder for chaining.
     */
    public Builder addAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureAddressIsMutable();
      address_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:chapter8.SubscribeReq)
  }

  // @@protoc_insertion_point(class_scope:chapter8.SubscribeReq)
  private static final com.example.netty.chapter8.pojo.SubscribeReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.netty.chapter8.pojo.SubscribeReq();
  }

  public static com.example.netty.chapter8.pojo.SubscribeReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubscribeReq>
      PARSER = new com.google.protobuf.AbstractParser<SubscribeReq>() {
    @java.lang.Override
    public SubscribeReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SubscribeReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SubscribeReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.netty.chapter8.pojo.SubscribeReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

