// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SubscribeReq.proto
// Protobuf Java Version: 4.27.0

package com.example.netty.chapter8.pojo;

public final class SubscribeReqProtos {
  private SubscribeReqProtos() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      SubscribeReqProtos.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chapter8_SubscribeReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chapter8_SubscribeReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022SubscribeReq.proto\022\010chapter8\"X\n\014Subscr" +
      "ibeReq\022\020\n\010subReqId\030\001 \001(\005\022\020\n\010userName\030\002 \001" +
      "(\t\022\023\n\013productName\030\003 \001(\t\022\017\n\007address\030\004 \003(\t" +
      "B7\n\037com.example.netty.chapter8.pojoB\022Sub" +
      "scribeReqProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_chapter8_SubscribeReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_chapter8_SubscribeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_chapter8_SubscribeReq_descriptor,
        new java.lang.String[] { "SubReqId", "UserName", "ProductName", "Address", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
