// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SubscribeReq.proto
// Protobuf Java Version: 4.27.0

package com.example.netty.chapter8.pojo;

public interface SubscribeReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chapter8.SubscribeReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 subReqId = 1;</code>
   * @return The subReqId.
   */
  int getSubReqId();

  /**
   * <code>string userName = 2;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 2;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string productName = 3;</code>
   * @return The productName.
   */
  java.lang.String getProductName();
  /**
   * <code>string productName = 3;</code>
   * @return The bytes for productName.
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>repeated string address = 4;</code>
   * @return A list containing the address.
   */
  java.util.List<java.lang.String>
      getAddressList();
  /**
   * <code>repeated string address = 4;</code>
   * @return The count of address.
   */
  int getAddressCount();
  /**
   * <code>repeated string address = 4;</code>
   * @param index The index of the element to return.
   * @return The address at the given index.
   */
  java.lang.String getAddress(int index);
  /**
   * <code>repeated string address = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the address at the given index.
   */
  com.google.protobuf.ByteString
      getAddressBytes(int index);
}
